from __future__ import annotations

import argparse
import json
from dataclasses import dataclass

from talkingboats.channel_metadata import CHANNEL_METADATA, VOICE_NET_BALANCED_CHANNELS


@dataclass(frozen=True)
class CaptureChannel:
    channel: str
    label: str
    frequency_hz: int
    slot_seconds: int | None = None


@dataclass(frozen=True)
class CaptureProfile:
    name: str
    mode: str
    channels: tuple[CaptureChannel, ...]
    center_frequency_hz: int | None = None
    sample_rate_hz: int | None = None


@dataclass(frozen=True)
class AirbandIcecastOutput:
    channel: str
    server: str
    port: int
    mountpoint: str
    name: str
    password: str
    username: str = "source"
    genre: str = "Marine VHF"
    continuous: bool = True


CAPTURE_PROFILES = {
    "debug": CaptureProfile(
        name="debug",
        mode="sequential",
        channels=(
            CaptureChannel(
                channel="14",
                label=CHANNEL_METADATA["14"].label,
                frequency_hz=CHANNEL_METADATA["14"].frequency_hz,
                slot_seconds=480,
            ),
        ),
    ),
    "elliott_bay": CaptureProfile(
        name="elliott_bay",
        mode="multichannel",
        center_frequency_hz=156_675_000,
        sample_rate_hz=2_560_000,
        channels=(
            CaptureChannel(
                channel="13",
                label=CHANNEL_METADATA["13"].label,
                frequency_hz=CHANNEL_METADATA["13"].frequency_hz,
            ),
            CaptureChannel(
                channel="14",
                label=CHANNEL_METADATA["14"].label,
                frequency_hz=CHANNEL_METADATA["14"].frequency_hz,
            ),
            CaptureChannel(
                channel="68",
                label=CHANNEL_METADATA["68"].label,
                frequency_hz=CHANNEL_METADATA["68"].frequency_hz,
            ),
        ),
    ),
    "voice_net_balanced": CaptureProfile(
        name="voice_net_balanced",
        mode="multichannel",
        center_frequency_hz=156_675_000,
        sample_rate_hz=2_560_000,
        channels=tuple(
            CaptureChannel(
                channel=channel,
                label=CHANNEL_METADATA[channel].label,
                frequency_hz=CHANNEL_METADATA[channel].frequency_hz,
            )
            for channel in VOICE_NET_BALANCED_CHANNELS
        ),
    ),
}


def render_rtlsdr_airband_config(
    profile: CaptureProfile,
    *,
    output_root: str,
    icecast_output: AirbandIcecastOutput | None = None,
    icecast_outputs: tuple[AirbandIcecastOutput, ...] = (),
    device_index: int = 0,
    device_serial: str | None = None,
    squelch_threshold: float | None = None,
    squelch_snr_threshold: float | None = None,
    channel_squelch_thresholds: dict[str, float] | None = None,
    channel_squelch_snr_thresholds: dict[str, float] | None = None,
) -> str:
    if profile.mode != "multichannel" or profile.center_frequency_hz is None:
        raise ValueError("only multichannel profiles can be rendered as RTLSDR-Airband config")
    if squelch_threshold is not None and squelch_snr_threshold is not None:
        raise ValueError("squelch_threshold and squelch_snr_threshold are mutually exclusive")
    threshold_overrides = _normalize_channel_float_overrides(channel_squelch_thresholds)
    snr_overrides = _normalize_channel_float_overrides(channel_squelch_snr_thresholds)
    conflicting_channels = sorted(set(threshold_overrides) & set(snr_overrides))
    if conflicting_channels:
        raise ValueError(
            "channel squelch threshold and SNR threshold are mutually exclusive: "
            + ", ".join(conflicting_channels)
        )
    cleaned_output_root = output_root.rstrip("/")
    selected_icecast_outputs = tuple(icecast_outputs)
    if icecast_output is not None:
        selected_icecast_outputs = (icecast_output, *selected_icecast_outputs)
    channels = ",\n".join(
        f"""    {{
      freq = {channel.frequency_hz};
      modulation = "nfm";
      label = "vhf-{channel.channel.lower()}";
{
            _render_channel_squelch(
                threshold_overrides.get(channel.channel, squelch_threshold)
                if channel.channel not in snr_overrides
                else None,
                snr_overrides.get(channel.channel, squelch_snr_threshold)
                if channel.channel not in threshold_overrides
                else None,
            )
        }
      outputs:
      (
{_render_channel_outputs(channel, cleaned_output_root, selected_icecast_outputs)}
      );
    }}"""
        for channel in profile.channels
    )
    return f"""# Generated by talkingboats.capture_profiles.
# This captures nearby Elliott Bay marine VHF channels with one RTL-SDR.

devices:
({{
  type = "rtlsdr";
{_render_device_identifier(device_index, device_serial)}
  gain = 28;
  correction = 0;
  mode = "multichannel";
{_render_sample_rate(profile.sample_rate_hz)}
  centerfreq = {profile.center_frequency_hz};
  channels:
  (
{channels}
  );
}});
"""


def _render_channel_outputs(
    channel: CaptureChannel,
    output_root: str,
    icecast_outputs: tuple[AirbandIcecastOutput, ...],
) -> str:
    outputs = [
        f"""        {{
          type = "file";
          directory = {_config_string(f"{output_root}/{channel.channel}")};
          filename_template = "vhf-{channel.channel.lower()}";
          split_on_transmission = true;
          pre_roll_seconds = 0.50;
          post_roll_seconds = 0.75;
          attack_confirmation_batches = 2;
          minimum_active_batches = 3;
          maximum_transmission_seconds = 45;
        }}"""
    ]
    for icecast_output in icecast_outputs:
        if channel.channel != icecast_output.channel:
            continue
        outputs.append(
            f"""        {{
          type = "icecast";
          server = {_config_string(icecast_output.server)};
          port = {icecast_output.port};
          mountpoint = {_config_string(icecast_output.mountpoint.lstrip("/"))};
          name = {_config_string(icecast_output.name)};
          genre = {_config_string(icecast_output.genre)};
          username = {_config_string(icecast_output.username)};
          password = {_config_string(icecast_output.password)};
          continuous = {_config_bool(icecast_output.continuous)};
        }}"""
        )
    return ",\n".join(outputs)


def _render_device_identifier(device_index: int, device_serial: str | None) -> str:
    if device_serial:
        return f"  serial = {_config_string(device_serial)};"
    return f"  index = {device_index};"


def _render_sample_rate(sample_rate_hz: int | None) -> str:
    return f"  sample_rate = {sample_rate_hz};" if sample_rate_hz else ""


def _render_channel_squelch(
    squelch_threshold: float | None,
    squelch_snr_threshold: float | None,
) -> str:
    lines = []
    if squelch_threshold is not None:
        lines.append(f"      squelch_threshold = {_airband_number(squelch_threshold)};")
    if squelch_snr_threshold is not None:
        lines.append(f"      squelch_snr_threshold = {_airband_number(squelch_snr_threshold)};")
    return "\n".join(lines)


def _normalize_channel_float_overrides(
    overrides: dict[str, float] | None,
) -> dict[str, float]:
    normalized: dict[str, float] = {}
    for channel, value in (overrides or {}).items():
        rendered_channel = str(channel).strip().upper()
        if not rendered_channel:
            continue
        normalized[rendered_channel] = float(value)
    return normalized


def _airband_number(value: float) -> str:
    return str(int(value)) if value.is_integer() else f"{value:.1f}"


def _config_string(value: str) -> str:
    return json.dumps(value)


def _config_bool(value: bool) -> str:
    return "true" if value else "false"


def main() -> None:
    parser = argparse.ArgumentParser(description="Render Talking Boats capture profile configs.")
    parser.add_argument("--profile", choices=sorted(CAPTURE_PROFILES), required=True)
    parser.add_argument("--output-root", default="/opt/talkingboats/spool/airband")
    parser.add_argument("--device-index", type=int, default=0)
    parser.add_argument("--device-serial")
    parser.add_argument("--squelch-threshold", type=float)
    parser.add_argument("--squelch-snr-threshold", type=float)
    parser.add_argument("--channel-squelch-threshold", action="append", default=[])
    parser.add_argument("--channel-squelch-snr-threshold", action="append", default=[])
    parser.add_argument("--icecast-channel")
    parser.add_argument("--icecast-host", default="127.0.0.1")
    parser.add_argument("--icecast-port", type=int, default=8000)
    parser.add_argument("--icecast-mount", default="/talkingboats-live.mp3")
    parser.add_argument("--icecast-name", default="Talking Boats VHF 14")
    parser.add_argument(
        "--icecast-output",
        action="append",
        default=[],
        metavar="CHANNEL:MOUNT:NAME",
        help="Add one Icecast output using the shared Icecast host, port, and source password.",
    )
    parser.add_argument("--icecast-source-password")
    args = parser.parse_args()
    icecast_outputs = []
    if args.icecast_output:
        if not args.icecast_source_password:
            parser.error("--icecast-output requires --icecast-source-password")
        for spec in args.icecast_output:
            channel, mountpoint, name = _parse_icecast_output_spec(spec, parser)
            icecast_outputs.append(
                AirbandIcecastOutput(
                    channel=channel,
                    server=args.icecast_host,
                    port=args.icecast_port,
                    mountpoint=mountpoint,
                    name=name,
                    password=args.icecast_source_password,
                )
            )
    icecast_output = None
    if args.icecast_channel or args.icecast_source_password:
        if args.icecast_output and not args.icecast_channel:
            icecast_output = None
        elif not args.icecast_channel or not args.icecast_source_password:
            parser.error("--icecast-channel and --icecast-source-password must be used together")
        else:
            icecast_output = AirbandIcecastOutput(
                channel=args.icecast_channel,
                server=args.icecast_host,
                port=args.icecast_port,
                mountpoint=args.icecast_mount,
                name=args.icecast_name,
                password=args.icecast_source_password,
            )
    print(
        render_rtlsdr_airband_config(
            CAPTURE_PROFILES[args.profile],
            output_root=args.output_root,
            icecast_output=icecast_output,
            icecast_outputs=tuple(icecast_outputs),
            device_index=args.device_index,
            device_serial=args.device_serial,
            squelch_threshold=args.squelch_threshold,
            squelch_snr_threshold=args.squelch_snr_threshold,
            channel_squelch_thresholds=_parse_channel_float_specs(
                args.channel_squelch_threshold,
                parser,
            ),
            channel_squelch_snr_thresholds=_parse_channel_float_specs(
                args.channel_squelch_snr_threshold,
                parser,
            ),
        )
    )


def _parse_icecast_output_spec(
    value: str,
    parser: argparse.ArgumentParser,
) -> tuple[str, str, str]:
    parts = value.split(":", 2)
    if len(parts) != 3 or not all(parts):
        parser.error("--icecast-output must be CHANNEL:MOUNT:NAME")
    return parts[0], parts[1], parts[2]


def _parse_channel_float_specs(
    values: list[str],
    parser: argparse.ArgumentParser,
) -> dict[str, float]:
    parsed: dict[str, float] = {}
    for value in values:
        if "=" not in value:
            parser.error("channel squelch overrides must be CHANNEL=VALUE")
        channel, raw_number = value.split("=", 1)
        channel = channel.strip().upper()
        if not channel:
            parser.error("channel squelch override channel cannot be empty")
        try:
            parsed[channel] = float(raw_number)
        except ValueError:
            parser.error("channel squelch override value must be numeric")
    return parsed


if __name__ == "__main__":
    main()
