from __future__ import annotations

import argparse
from dataclasses import dataclass


@dataclass(frozen=True)
class CaptureChannel:
    channel: str
    label: str
    frequency_hz: int
    slot_seconds: int | None = None


@dataclass(frozen=True)
class CaptureProfile:
    name: str
    mode: str
    channels: tuple[CaptureChannel, ...]
    center_frequency_hz: int | None = None


CAPTURE_PROFILES = {
    "debug": CaptureProfile(
        name="debug",
        mode="sequential",
        channels=(
            CaptureChannel(
                channel="WX",
                label="NOAA Weather 162.550",
                frequency_hz=162_550_000,
                slot_seconds=120,
            ),
            CaptureChannel(
                channel="14",
                label="VTS / Seattle Traffic",
                frequency_hz=156_700_000,
                slot_seconds=480,
            ),
        ),
    ),
    "elliott_bay": CaptureProfile(
        name="elliott_bay",
        mode="multichannel",
        center_frequency_hz=156_675_000,
        channels=(
            CaptureChannel(
                channel="13",
                label="Bridge-to-bridge",
                frequency_hz=156_650_000,
            ),
            CaptureChannel(
                channel="14",
                label="VTS / Seattle Traffic",
                frequency_hz=156_700_000,
            ),
        ),
    ),
}


def render_rtlsdr_airband_config(profile: CaptureProfile, *, output_root: str) -> str:
    if profile.mode != "multichannel" or profile.center_frequency_hz is None:
        raise ValueError("only multichannel profiles can be rendered as RTLSDR-Airband config")
    cleaned_output_root = output_root.rstrip("/")
    channels = ",\n".join(
        f"""    {{
      freq = {channel.frequency_hz};
      modulation = "nfm";
      label = "vhf-{channel.channel.lower()}";
      outputs:
      (
        {{
          type = "rawfile";
          directory = "{cleaned_output_root}/{channel.channel}";
          filename_template = "vhf-{channel.channel.lower()}";
          split_on_transmission = true;
        }}
      );
    }}"""
        for channel in profile.channels
    )
    return f"""# Generated by talkingboats.capture_profiles.
# This captures nearby Elliott Bay marine VHF channels with one RTL-SDR.

devices:
({{
  type = "rtlsdr";
  index = 0;
  gain = 28;
  correction = 0;
  mode = "multichannel";
  centerfreq = {profile.center_frequency_hz};
  channels:
  (
{channels}
  );
}});
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Render Talking Boats capture profile configs.")
    parser.add_argument("--profile", choices=sorted(CAPTURE_PROFILES), required=True)
    parser.add_argument("--output-root", default="/opt/talkingboats/spool/airband")
    args = parser.parse_args()
    print(
        render_rtlsdr_airband_config(
            CAPTURE_PROFILES[args.profile],
            output_root=args.output_root,
        )
    )


if __name__ == "__main__":
    main()
