services:
  vhf-dev-proxy:
    container_name: vhf-dev-tailnet-proxy
    image: nginx:1.27-alpine
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/.local/share/talkingboats/certbot/config:/etc/letsencrypt:ro
      - /home/rob/pihole-docker/etc-pihole:/etc/nginx/pihole:ro
